[book]
authors = ["kingdom"]
language = "zh"
multilingual = false
src = "src"
title = "AI技术栈解析及应用- 作者：张真瑜 | 山东大学智能创新研究院"  "
description = "AI Technology Stack - 一个全面的AI技术知识体系文档 | 作者：张真瑜 | 山东大学智能创新研究院（Academy of Intelligent Innovation）© 2024" 
